# Generated by Django 4.2 on 2024-09-19 21:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_alter_diary_loc_x_alter_diary_loc_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='photos/'),
        ),
    ]
