# Generated by Django 4.2 on 2024-09-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='cinema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='loc_x',
            field=models.DecimalField(decimal_places=4, default=33.4507, max_digits=4),
        ),
        migrations.AddField(
            model_name='diary',
            name='loc_y',
            field=models.DecimalField(decimal_places=4, default=126.5706, max_digits=4),
        ),
    ]
